language: julia

os:
  - linux

julia:
  - 1.3

notifications:
  email: false

env:
  global:
    BINARYBUILDER_AUTOMATIC_APPLE=true

jobs:
  include:
    # 10.1
    - name: "CUDA 10.1 for Linux"
      env: TARGET=x86_64-linux-gnu VERSION=10.1
    - name: "CUDA 10.1 for macOS"
      env: TARGET=x86_64-apple-darwin14 VERSION=10.1
    - name: "CUDA 10.1 for Windows"
      env: TARGET=x86_64-w64-mingw32 VERSION=10.1
    # 10.0
    - name: "CUDA 10.0 for Linux"
      env: TARGET=x86_64-linux-gnu VERSION=10.0
    - name: "CUDA 10.0 for macOS"
      env: TARGET=x86_64-apple-darwin14 VERSION=10.0
    - name: "CUDA 10.0 for Windows"
      env: TARGET=x86_64-w64-mingw32 VERSION=10.0
    # 9.2
    - name: "CUDA 9.2 for Linux"
      env: TARGET=x86_64-linux-gnu VERSION=9.2
    - name: "CUDA 9.2 for macOS"
      env: TARGET=x86_64-apple-darwin14 VERSION=9.2
    - name: "CUDA 9.2 for Windows"
      env: TARGET=x86_64-w64-mingw32 VERSION=9.2
    # 9.0
    - name: "CUDA 9.0 for Linux"
      env: TARGET=x86_64-linux-gnu VERSION=9.0
    - name: "CUDA 9.0 for macOS"
      env: TARGET=x86_64-apple-darwin14 VERSION=9.0
    - name: "CUDA 9.0 for Windows"
      env: TARGET=x86_64-w64-mingw32 VERSION=9.0

before_script:
  - julia -e 'using Pkg; Pkg.instantiate()'

script:
  - julia --color=yes build_tarballs.jl --verbose --version=$VERSION $TARGET

# deploy:
#   provider: releases
#   api_key:
#     secure: ...
#   file_glob: true
#   file: products/*
#   skip_cleanup: true
#   on:
#     repo: JuliaGPU/CUDABuilder
#     tags: true
